"""AI digest generation with a free-tier model fallback chain."""

from __future__ import annotations

import json
import logging
import os

import httpx
from google import genai
from google.genai import types

from src.config import (
    DIGEST_PROMPT_TEMPLATE,
    FALLBACK_HEADLINES_TEMPLATE,
    GEMINI_FALLBACK_MODELS,
    GEMINI_MODEL,
    MAX_OUTPUT_TOKENS,
    OPENAI_COMPAT_FALLBACKS,
    READER_PERSONA,
    SLOT_INSTRUCTIONS,
    TRUNCATION_NOTICE,
)
from src.fetcher import Article, format_headlines_fallback

logger = logging.getLogger(__name__)


def generate_digest(
    articles: list[Article],
    slot: str = "morning",
    storylines_json: str = "[]",
) -> tuple[str, bool]:
    """
    Generate markdown digest via the model fallback chain.

    Returns (markdown_content, used_ai).
    """
    if not articles:
        return "# Nigeria & Tech Brief\n\nNo major updates in this window.", True

    def build_prompt(include_full_text: bool) -> str:
        articles_json = json.dumps(
            [a.to_compact_dict(include_full_text=include_full_text) for a in articles],
            indent=2,
        )
        return DIGEST_PROMPT_TEMPLATE.format(
            persona=READER_PERSONA,
            slot_instructions=SLOT_INSTRUCTIONS.get(slot, SLOT_INSTRUCTIONS["morning"]),
            storylines_json=storylines_json,
            articles_json=articles_json,
        )

    # Full text only for Gemini (1M context); fallback models get summaries only
    text = generate_text(build_prompt(True), fallback_prompt=build_prompt(False))
    if text:
        return text, True
    return _headline_fallback(articles), False


def generate_text(prompt: str, fallback_prompt: str | None = None) -> str | None:
    """
    Try each model in the free-tier chain; return markdown or None if all fail.

    Chain: Gemini flash -> Gemini flash-lite -> any configured
    OpenAI-compatible provider (Cerebras, Groq). The OpenAI-compatible
    providers receive `fallback_prompt` (a smaller prompt) when given, since
    their context/TPM limits are far below Gemini's.
    """
    gemini_key = os.environ.get("GEMINI_API_KEY")
    if gemini_key:
        client = genai.Client(api_key=gemini_key)
        for model in [GEMINI_MODEL, *GEMINI_FALLBACK_MODELS]:
            try:
                return _gemini_generate(client, model, prompt)
            except Exception as exc:
                logger.warning("Gemini model %s failed: %s", model, exc)
    else:
        logger.warning("GEMINI_API_KEY not set; skipping Gemini")

    for env_var, url, model in OPENAI_COMPAT_FALLBACKS:
        api_key = os.environ.get(env_var)
        if not api_key:
            continue
        try:
            return _openai_compat_generate(url, api_key, model, fallback_prompt or prompt)
        except Exception as exc:
            logger.warning("Fallback %s (%s) failed: %s", model, url, exc)

    logger.error("All AI models in the fallback chain failed")
    return None


def generate_json(prompt: str, max_tokens: int = 4096) -> list | dict | None:
    """Gemini JSON-mode generation (used for storyline tracking). Best effort."""
    gemini_key = os.environ.get("GEMINI_API_KEY")
    if not gemini_key:
        return None

    client = genai.Client(api_key=gemini_key)
    for model in [GEMINI_MODEL, *GEMINI_FALLBACK_MODELS]:
        try:
            response = client.models.generate_content(
                model=model,
                contents=prompt,
                config=types.GenerateContentConfig(
                    max_output_tokens=max_tokens,
                    temperature=0.2,
                    response_mime_type="application/json",
                ),
            )
            text = (response.text or "").strip()
            if text:
                return json.loads(text)
        except Exception as exc:
            logger.warning("JSON generation with %s failed: %s", model, exc)
    return None


def _gemini_generate(client: genai.Client, model: str, prompt: str) -> str:
    response = client.models.generate_content(
        model=model,
        contents=prompt,
        config=types.GenerateContentConfig(
            max_output_tokens=MAX_OUTPUT_TOKENS,
            temperature=0.4,
        ),
    )
    text = (response.text or "").strip()
    if not text:
        raise ValueError("Empty response")

    finish_reason = _get_finish_reason(response)
    if _was_truncated(finish_reason):
        logger.warning(
            "Gemini output truncated (model=%s, finish_reason=%s, max_tokens=%d)",
            model,
            finish_reason,
            MAX_OUTPUT_TOKENS,
        )
        text = _append_truncation_notice(text, finish_reason)

    logger.info("Digest generated by %s", model)
    return text


def _openai_compat_generate(url: str, api_key: str, model: str, prompt: str) -> str:
    response = httpx.post(
        url,
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.4,
            "max_tokens": 8192,
        },
        timeout=120.0,
    )
    response.raise_for_status()
    text = (response.json()["choices"][0]["message"]["content"] or "").strip()
    if not text:
        raise ValueError("Empty response")
    logger.info("Digest generated by fallback %s", model)
    return text


def _get_finish_reason(response) -> str | None:
    candidates = getattr(response, "candidates", None) or []
    if not candidates:
        return None
    reason = getattr(candidates[0], "finish_reason", None)
    if reason is None:
        return None
    return str(reason)


def _was_truncated(finish_reason: str | None) -> bool:
    if not finish_reason:
        return False
    normalized = finish_reason.upper()
    return "MAX_TOKENS" in normalized


def _append_truncation_notice(text: str, finish_reason: str | None) -> str:
    notice = TRUNCATION_NOTICE.strip()
    if finish_reason:
        notice = notice.replace(
            "cut short because the AI hit its output limit.",
            f"cut short because the AI hit its output limit ({finish_reason}).",
        )
    return f"{text}\n\n{notice}"


def _headline_fallback(articles: list[Article]) -> str:
    headlines = format_headlines_fallback(articles)
    return FALLBACK_HEADLINES_TEMPLATE.format(headlines=headlines)
